// Copyright 2018-2024 the Deno authors. All rights reserved. MIT license.

use super::Context;
use super::LintRule;
use crate::diagnostic::LintFix;
use crate::diagnostic::LintFixChange;
use crate::handler::Handler;
use crate::tags;
use crate::tags::Tags;

use deno_ast::oxc::ast::ast::{
  ComputedMemberExpression, Expression, MemberExpression, Program,
  StaticMemberExpression, TemplateLiteral,
};
use if_chain::if_chain;
use once_cell::sync::Lazy;
use std::collections::HashSet;

#[derive(Debug)]
pub struct NoWindowPrefix;

const CODE: &str = "no-window-prefix";
const MESSAGE: &str = "For compatibility between the Window context and the Web Workers, calling Web APIs via `window` is disallowed";
const HINT: &str =
  "Instead, call this API via `self`, `globalThis`, or no extra prefix";
const FIX_DESC: &str = "Rename window to globalThis";

impl LintRule for NoWindowPrefix {
  fn tags(&self) -> Tags {
    &[tags::RECOMMENDED]
  }

  fn code(&self) -> &'static str {
    CODE
  }

  fn lint_program_with_ast_view<'a>(
    &self,
    context: &mut Context<'a>,
    program: &Program<'a>,
  ) {
    let mut handler = NoWindowPrefixHandler {
      in_member_expr_object: false,
    };
    crate::handler::traverse_program(&mut handler, program, context);
  }
}

// Auto-generated by tools/generate_no_window_prefix_deny_list.ts
static PROPERTY_DENY_LIST: Lazy<HashSet<&'static str>> = Lazy::new(|| {
  [
    "AbortController",
    "AbortSignal",
    "Blob",
    "BroadcastChannel",
    "ByteLengthQueuingStrategy",
    "Cache",
    "CacheStorage",
    "CanvasGradient",
    "CanvasPattern",
    "CloseEvent",
    "CountQueuingStrategy",
    "Crypto",
    "CryptoKey",
    "CustomEvent",
    "DOMException",
    "DOMMatrix",
    "DOMMatrixReadOnly",
    "DOMPoint",
    "DOMPointReadOnly",
    "DOMQuad",
    "DOMRect",
    "DOMRectReadOnly",
    "DOMStringList",
    "ErrorEvent",
    "Event",
    "EventSource",
    "EventTarget",
    "File",
    "FileList",
    "FileReader",
    "FontFace",
    "FontFaceSet",
    "FontFaceSetLoadEvent",
    "FormData",
    "Headers",
    "IDBCursor",
    "IDBCursorWithValue",
    "IDBDatabase",
    "IDBFactory",
    "IDBIndex",
    "IDBKeyRange",
    "IDBObjectStore",
    "IDBOpenDBRequest",
    "IDBRequest",
    "IDBTransaction",
    "IDBVersionChangeEvent",
    "ImageBitmap",
    "ImageBitmapRenderingContext",
    "ImageData",
    "MediaCapabilities",
    "MessageChannel",
    "MessageEvent",
    "MessagePort",
    "NetworkInformation",
    "Notification",
    "Path2D",
    "Performance",
    "PerformanceEntry",
    "PerformanceMark",
    "PerformanceMeasure",
    "PerformanceObserver",
    "PerformanceObserverEntryList",
    "PerformanceResourceTiming",
    "PerformanceServerTiming",
    "PermissionStatus",
    "Permissions",
    "ProgressEvent",
    "PromiseRejectionEvent",
    "PushManager",
    "PushSubscription",
    "PushSubscriptionOptions",
    "ReadableStream",
    "ReadableStreamDefaultController",
    "ReadableStreamDefaultReader",
    "Request",
    "Response",
    "SecurityPolicyViolationEvent",
    "ServiceWorker",
    "ServiceWorkerContainer",
    "ServiceWorkerRegistration",
    "StorageManager",
    "SubtleCrypto",
    "TextDecoder",
    "TextDecoderStream",
    "TextEncoder",
    "TextEncoderStream",
    "TextMetrics",
    "TransformStream",
    "TransformStreamDefaultController",
    "URL",
    "URLSearchParams",
    "WebGL2RenderingContext",
    "WebGLActiveInfo",
    "WebGLBuffer",
    "WebGLContextEvent",
    "WebGLFramebuffer",
    "WebGLProgram",
    "WebGLQuery",
    "WebGLRenderbuffer",
    "WebGLRenderingContext",
    "WebGLSampler",
    "WebGLShader",
    "WebGLShaderPrecisionFormat",
    "WebGLSync",
    "WebGLTexture",
    "WebGLTransformFeedback",
    "WebGLUniformLocation",
    "WebGLVertexArrayObject",
    "WebSocket",
    "Worker",
    "WritableStream",
    "WritableStreamDefaultController",
    "WritableStreamDefaultWriter",
    "XMLHttpRequest",
    "XMLHttpRequestEventTarget",
    "XMLHttpRequestUpload",
    "console",
    "WebAssembly",
    "name",
    "navigator",
    "self",
    "close",
    "postMessage",
    "dispatchEvent",
    "cancelAnimationFrame",
    "requestAnimationFrame",
    "onerror",
    "onlanguagechange",
    "onmessage",
    "onmessageerror",
    "onoffline",
    "ononline",
    "onrejectionhandled",
    "onunhandledrejection",
    "caches",
    "crossOriginIsolated",
    "crypto",
    "indexedDB",
    "isSecureContext",
    "origin",
    "performance",
    "atob",
    "btoa",
    "clearInterval",
    "clearTimeout",
    "createImageBitmap",
    "fetch",
    "queueMicrotask",
    "setInterval",
    "setTimeout",
    "addEventListener",
    "removeEventListener",
    "Deno",
  ]
  .iter()
  .copied()
  .collect()
});

/// Extracts the property symbol from a StaticMemberExpression.
fn extract_symbol_static<'a>(
  expr: &'a StaticMemberExpression<'a>,
) -> Option<&'a str> {
  Some(expr.property.name.as_str())
}

/// Extracts the property symbol from a ComputedMemberExpression, if statically determinable.
fn extract_symbol_computed<'a>(
  expr: &'a ComputedMemberExpression<'a>,
) -> Option<&'a str> {
  match &expr.expression {
    Expression::StringLiteral(s) => Some(s.value.as_str()),
    Expression::TemplateLiteral(tpl) => {
      let TemplateLiteral {
        expressions,
        quasis,
        ..
      } = &**tpl;
      if expressions.is_empty() && quasis.len() == 1 {
        Some(quasis[0].value.raw.as_str())
      } else {
        None
      }
    }
    // If it's a computed identifier like `window[bar]`, skip
    Expression::Identifier(_) => None,
    _ => None,
  }
}

struct NoWindowPrefixHandler {
  /// Track whether we're inside a member expression's object position.
  /// This replaces the old `.parent().is::<MemberExpr>()` check.
  in_member_expr_object: bool,
}

impl NoWindowPrefixHandler {
  fn is_window_global(
    &self,
    ident: &deno_ast::oxc::ast::ast::IdentifierReference,
    ctx: &Context,
  ) -> bool {
    if ident.name != "window" {
      return false;
    }
    if let Some(ref_id) = ident.reference_id.get() {
      let reference = ctx.scoping().get_reference(ref_id);
      if reference.symbol_id().is_some() {
        return false;
      }
    }
    true
  }

  fn check_member_expr(
    &mut self,
    object: &Expression,
    prop_symbol: Option<&str>,
    full_span: deno_ast::oxc::span::Span,
    obj_span: deno_ast::oxc::span::Span,
    ctx: &mut Context,
  ) {
    // Don't check chained member expressions (e.g. `foo.bar.baz`)
    // When we're inside a member expression's object, skip.
    if self.in_member_expr_object {
      return;
    }

    if_chain! {
      if let Expression::Identifier(obj_ident) = object;
      if self.is_window_global(obj_ident, ctx);
      if let Some(prop_sym) = prop_symbol;
      if PROPERTY_DENY_LIST.contains(prop_sym);
      then {
        ctx.add_diagnostic_with_fixes(
          full_span,
          CODE,
          MESSAGE,
          Some(HINT.into()),
          vec![LintFix {
            description: FIX_DESC.into(),
            changes: vec![LintFixChange {
              new_text: "globalThis".into(),
              range: obj_span,
            }],
          }]
        );
      }
    }
  }
}

impl Handler<'_> for NoWindowPrefixHandler {
  fn member_expression(
    &mut self,
    member_expr: &MemberExpression,
    _ctx: &mut Context,
  ) {
    // Set the flag to indicate we're entering a member expression.
    // This is used by static/computed member expression handlers
    // to detect chaining. The member_expression handler fires before
    // the specific variant handlers, and child member expressions
    // in object position will see this flag as true.
    //
    // Note: We need to detect when the *object* of a member expression
    // is itself a member expression. We do this by setting a flag
    // here that child member expressions check.
    let _ = member_expr;
  }

  fn static_member_expression(
    &mut self,
    expr: &StaticMemberExpression,
    ctx: &mut Context,
  ) {
    let prop_symbol = extract_symbol_static(expr);

    // Check if this member expression's object is also a member expression
    // (i.e., we're in a chain like `window.fetch.bar`). In that case, the
    // inner `window.fetch` should not be separately reported.
    let was_in = self.in_member_expr_object;
    // We want to report only the outermost member expression.
    // If our object is itself a member expression, mark that we're in chain.
    // But WE should still check (we're the outermost).
    // Actually, the traversal visits this node first, then descends into object.
    // So we should check ourselves, then set the flag for children.
    self.check_member_expr(
      &expr.object,
      prop_symbol,
      expr.span,
      match &expr.object {
        Expression::Identifier(ident) => ident.span,
        _ => expr.span,
      },
      ctx,
    );
    // The flag approach won't work directly since traversal happens after.
    // Instead, we rely on the fact that our check only matches when object
    // is an Identifier (not a MemberExpression), so chaining is naturally handled.
    self.in_member_expr_object = was_in;
  }

  fn computed_member_expression(
    &mut self,
    expr: &ComputedMemberExpression,
    ctx: &mut Context,
  ) {
    let prop_symbol = extract_symbol_computed(expr);
    self.check_member_expr(
      &expr.object,
      prop_symbol,
      expr.span,
      match &expr.object {
        Expression::Identifier(ident) => ident.span,
        _ => expr.span,
      },
      ctx,
    );
  }
}

#[cfg(test)]
mod tests {
  use super::*;

  #[test]
  fn no_window_prefix_valid() {
    assert_lint_ok! {
      NoWindowPrefix,
      "fetch();",
      "self.fetch();",
      "globalThis.fetch();",

      "Deno.metrics();",
      "self.Deno.metrics();",
      "globalThis.Deno.metrics();",

      "onload();",
      "self.onload();",
      "globalThis.onload();",
      "window.onload();",
      r#"window["onload"]();"#,
      r#"window[`onload`]();"#,

      "onunload();",
      "self.onunload();",
      "globalThis.onunload();",
      "window.onunload();",
      r#"window["onunload"]();"#,
      r#"window[`onunload`]();"#,

      "closed;",
      "self.closed;",
      "globalThis.closed;",
      "window.closed;",
      r#"window["closed"];"#,
      r#"window[`closed`];"#,

      "alert();",
      "self.alert();",
      "globalThis.alert();",
      "window.alert();",
      r#"window["alert"]();"#,
      r#"window[`alert`]();"#,

      "confirm();",
      "self.confirm();",
      "globalThis.confirm();",
      "window.confirm();",
      r#"window["confirm"]();"#,
      r#"window[`confirm`]();"#,

      "prompt();",
      "self.prompt();",
      "globalThis.prompt();",
      "window.prompt();",
      r#"window["prompt"]();"#,
      r#"window[`prompt`]();"#,

      "localStorage;",
      "self.localStorage;",
      "globalThis.localStorage;",
      "window.localStorage;",
      r#"window["localStorage"];"#,
      r#"window[`localStorage`];"#,

      "sessionStorage;",
      "self.sessionStorage;",
      "globalThis.sessionStorage;",
      "window.sessionStorage;",
      r#"window["sessionStorage"];"#,
      r#"window[`sessionStorage`];"#,

      "window;",
      "self.window;",
      "globalThis.window;",
      "window.window;",
      r#"window["window"];"#,
      r#"window[`window`];"#,

      "Navigator;",
      "self.Navigator;",
      "globalThis.Navigator;",
      "window.Navigator;",
      r#"window["Navigator"];"#,
      r#"window[`Navigator`];"#,

      "location;",
      "self.location;",
      "globalThis.location;",
      "window.location;",
      r#"window["location"];"#,
      r#"window[`location`];"#,

      "history;",
      "self.history;",
      "globalThis.history;",
      "window.history;",
      r#"window["history"];"#,
      r#"window[`history`];"#,

      // `window` is shadowed
      "const window = 42; window.fetch();",
      r#"const window = 42; window["fetch"]();"#,
      r#"const window = 42; window[`fetch`]();"#,
      "const window = 42; window.alert();",
      r#"const window = 42; window["alert"]();"#,
      r#"const window = 42; window[`alert`]();"#,

      // Ignore property access with variables
      r#"const f = "fetch"; window[f]();"#,
      r#"const f = "fetch"; window[`${f}`]();"#,

      // Make sure that no false positives are triggered on chained member
      // expressions
      r#"foo.window.fetch();"#,
    };
  }

  #[test]
  fn no_window_prefix_invalid() {
    assert_lint_err! {
      NoWindowPrefix,
      MESSAGE,
      HINT,
      r#"window.fetch()"#: [
        {
          col: 0,
          fix: (FIX_DESC, "globalThis.fetch()"),
        }
      ],
      r#"window["fetch"]()"#: [
        {
          col: 0,
          fix: (FIX_DESC, r#"globalThis["fetch"]()"#),
        }
      ],
      r#"window[`fetch`]()"#: [
        {
          col: 0,
          fix: (FIX_DESC, "globalThis[`fetch`]()"),
        }
      ],
      "
function foo() {
  const window = 42;
  return window;
}
window.fetch();": [
        {
          col: 0,
          line: 6,
          fix: (FIX_DESC, "
function foo() {
  const window = 42;
  return window;
}
globalThis.fetch();"),
        }
      ],
    };
  }
}
