// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $ignoring_rules from "./routes/ignoring-rules.tsx";
import * as $index from "./routes/index.tsx";
import * as $rules_name_ from "./routes/rules/[name].tsx";

import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/ignoring-rules.tsx": $ignoring_rules,
    "./routes/index.tsx": $index,
    "./routes/rules/[name].tsx": $rules_name_,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
