name: release

on:
  workflow_dispatch:
    inputs:
      releaseKind:
        description: "Kind of release"
        default: "minor"
        type: choice
        options:
          - patch
          - minor
        required: true

jobs:
  rust:
    name: release
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.DENOBOT_PAT }}

      - uses: denoland/setup-deno@v1
      - uses: dtolnay/rust-toolchain@stable

      - name: Tag and release
        env:
          GITHUB_TOKEN: ${{ secrets.DENOBOT_PAT }}
          GH_WORKFLOW_ACTOR: ${{ github.actor }}
        run: |
          git config user.email "denobot@users.noreply.github.com"
          git config user.name "denobot"
          deno run -A https://raw.githubusercontent.com/denoland/automation/0.16.1/tasks/publish_release.ts --${{github.event.inputs.releaseKind}}
